# -*- coding: utf-8 -*-
"""TP1_IAI4_0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zI6OZ778oW0ugXJ9G2wdqjrygwuKbaOO

**TP 1 : Machine Learning pour le contrôle de qualité**

**1. Objectif**

L’objectif de ce TP est de développer un modèle de classification pour le contrôle qualité des puces
semi-conductrices.
"""

!pip install imblearn

""" **2.Prise en main de la dataset**"""

#Import librairies de manipulation et de visualisation

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Importation de la dataset

file_path = "/content/uci-secom.csv"
data = pd.read_csv(file_path)

#Afficher les dimensions du dataframe

print(data.shape)

#Afficher les 10 premières lignes

data.head(10)

"""Interprétation :
- Valeurs manquantes
- Variances élévés par rapport aux valeurs des colonnes
- Les colonnes nécessitent une standarisation ou une normalisation
- Les étiquettes de colonnes sont de catégories différentes (phase/aux autres colonnes)
- Le capteur No 5 affiche la meme valeur plusieurs fois en première constation
- Le capteur No 583 admet des différence de valeur d'ordre de 10x2
"""

#Utiliser la méthode info() pour afficher les détails des colonnes

data.info()

"""Commentaire 🇰
- 590 colonnes de type float (nombre à virgule)
- 1 colonne de type entier(probablement la target)
- 2 colonne de type objet( à encoder surement)
"""

#Utiliser la méthode describe() pour afficher les quelques statistiques sur les données

data.describe()

"""Commentaires
- La variance du feature N05 est nulles
- Les variances sont très différentes donc standarisation des colonnes
-colonnes à faible variance donc suppression imminente car n'impacte pas la target
"""

#Detection des valeurs manquantes

data.isnull().sum()

"""Commentaire :  colonnes ayant des valeurs manquantes très élevées"""

# Vérification des doublons

data.duplicated().sum()

"""Commentaire : Aucune donnée repétée"""

# Vérification de l'équilibrage des classes

data['Pass/Fail'].value_counts()

"""Commentaire : les données sont fortement déséquilibrées

**3.Analyse et prétraitement des données**
"""

#Vérifier les types de données des différentes colonnes

"""Différentes opérations à faire:
- Encoder la colonne Phase avec la méthode labelencoder pour éviter d'augementer
- Equilibrage des données
- supprimer la colonne time car pas importante
- Standarisation de toutes les colonnes
- Suppression des colonnes à faibles variances
- normalisation des colonnes
- Suppression des colonnes avec des valeurs manquantes elevées


"""

#encoder la colonne Phase avec le levelencoder
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
data['Phase'] = encoder.fit_transform(data['Phase'])

data.head(10)

#suppession de la colonne time

data.drop('Time', axis=1, inplace=True)
data.head(10)

#suppression des colonnes à faible variance
col = data[['Phase','Pass/Fail']] # Changed to list of columns
data.drop(col, axis=1, inplace=True)

# Calculer l'écart type de chaque colonne
ecarts_types = data.std()

# Définir le seuil d'écart type
seuil_ecart_type = 10  # Par exemple

# Sélectionner les colonnes à conserver
colonnes_a_conserver = ecarts_types[ecarts_types > seuil_ecart_type].index

# Créer un nouveau DataFrame avec les colonnes sélectionnées
new_data = data[colonnes_a_conserver]

final_df = pd.concat([new_data, col], axis=1) # Concatenate back

final_df.head(10)

#Detection des valeurs manquantes

missing_values = final_df.isnull().sum()
print(missing_values)

from typing_extensions import final
#suppression des colonnes avec plusieurs valeurs manquantes

# Sélectionner les colonnes à supprimer
columns_to_drop = missing_values[missing_values > 1].index

# Supprimer les colonnes du DataFrame
final_df = final_df.drop(columns=columns_to_drop)

final_df.head(10)

final_df.shape

#Remplacer les valeurs manquantes par leur le plus proche voisin

from sklearn.impute import KNNImputer

# Créer une instance de KNNImputer
imputer = KNNImputer(n_neighbors=3)  # Vous pouvez ajuster le nombre de voisins si nécessaire

# Ajuster l'imputer aux données et les transformer
data_imputed = imputer.fit_transform(final_df)

# Créer un nouveau DataFrame avec les valeurs imputées
final_df_imputed = pd.DataFrame(data_imputed, columns=final_df.columns)

final_df_imputed.head(10)

final_df_imputed.isnull().sum()

#Equilibrage des classes

from imblearn.over_sampling import SMOTE

# Instancier SMOTE
smote = SMOTE(random_state=42)

# Diviser les données
X = final_df_imputed.drop('Pass/Fail', axis=1)
y = final_df_imputed['Pass/Fail']

# Appliquer SMOTE
X_resampled, y_resampled = smote.fit_resample(X, y)

# Créer un nouveau DataFrame
balanced_df = pd.DataFrame(X_resampled, columns=X.columns)
balanced_df['Pass/Fail'] = y_resampled

balanced_df.head(10)
balanced_df['Pass/Fail'].value_counts()

#standarisation

import pandas as pd
from sklearn.preprocessing import StandardScaler
import joblib

# Instancier le StandardScaler
scaler = StandardScaler()

# Ajuster le scaler aux données et les transformer
X_scaled = scaler.fit_transform(balanced_df.drop('Pass/Fail', axis=1))

# Créer un nouveau DataFrame avec les données standardisées
scaled_df = pd.DataFrame(X_scaled, columns=balanced_df.drop('Pass/Fail', axis=1).columns)
scaled_df['Pass/Fail'] = balanced_df['Pass/Fail']

# Archiver le modèle avec Joblib
joblib.dump(scaler, 'scaler_model.pkl')

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import joblib

# Instancier le MinMaxScaler
normalizer = MinMaxScaler()

# Ajuster le normalisateur aux données et les transformer
X_normalized = normalizer.fit_transform(scaled_df.drop('Pass/Fail', axis=1))

# Créer un nouveau DataFrame avec les données normalisées
normalized_df = pd.DataFrame(X_normalized, columns=scaled_df.drop('Pass/Fail', axis=1).columns)
normalized_df['Pass/Fail'] = scaled_df['Pass/Fail']

# Archiver le modèle avec Joblib
joblib.dump(normalizer, 'normalizer_model.pkl')

import pandas as pd
from sklearn.decomposition import PCA
import joblib

# Instancier le PCA
pca = PCA(n_components=0.95)

# Ajuster le PCA aux données et les transformer
X_pca = pca.fit_transform(normalized_df.drop('Pass/Fail', axis=1))

# Créer un nouveau DataFrame avec les composantes principales
pca_df = pd.DataFrame(X_pca)
pca_df['Pass/Fail'] = normalized_df['Pass/Fail']

# Archiver le modèle avec Joblib
joblib.dump(pca, 'pca_model.pkl')

pca_df.head()

# Afficher les boxplots pour toutes les colonnes numériques

plt.figure(figsize=(12, 6))
sns.boxplot(data=pca_df)
plt.xticks(rotation=45)  # Rotation des noms de colonnes si nécessaire
plt.title("Détection des valeurs aberrantes")
plt.show()

# Définition d'une fonction pour détecter et supprimer les outliers
def remove_outliers(df):
    Q1 = df.quantile(0.25)  # 1er quartile
    Q3 = df.quantile(0.75)  # 3e quartile
    IQR = Q3 - Q1  # Interquartile Range

    # Définir les bornes pour détecter les outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    # Filtrer les données sans outliers
    df_cleaned = df[~((df < lower_bound) | (df > upper_bound)).any(axis=1)]

    return df_cleaned

# Supprimer les valeurs aberrantes
pca_df_cleaned = remove_outliers(pca_df)

print(f"Taille avant nettoyage : {pca_df.shape}")
print(f"Taille après nettoyage : {pca_df_cleaned.shape}")

#Visualisation après nettoyage

plt.figure(figsize=(12, 6))
sns.boxplot(data=pca_df_cleaned)
plt.xticks(rotation=45)
plt.title("Données après suppression des outliers")
plt.show()

#Visualiser la distribution des données

# Histogramme de toutes les colonnes numériques
pca_df_cleaned.hist(figsize=(12, 8), bins=30, edgecolor='black')
plt.suptitle("Distribution des variables")
plt.show()

# Courbes de densité (plus lisible que l'histogramme)
pca_df_cleaned.plot(kind='kde', figsize=(12, 6), title="Densité des variables")
plt.show()

# Calculer la matrice de corrélation
correlation_matrix = pca_df_cleaned.corr()

# Créer la heatmap
plt.figure(figsize=(10, 8))  # Ajuster la taille de la figure si nécessaire
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Matrice de corrélation')
plt.show()

"""**4.Lancement de l'apprentissage**"""

# Diviser les données en ensembles d'entraînement et de test
from sklearn.model_selection import train_test_split

X = pca_df_cleaned.drop('Pass/Fail', axis=1)
y = pca_df_cleaned['Pass/Fail']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)  # 70% pour l'entraînement, 20% pour le test

#entrainement des modèles

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import matplotlib.pyplot as plt

# Instancier les modèles avec des hyperparamètres
decision_tree = DecisionTreeClassifier(max_depth = 12, min_samples_split=8)
random_forest = RandomForestClassifier(n_estimators=200, max_depth=12)
# Entraîner les modèles
decision_tree.fit(X_train, y_train)
random_forest.fit(X_train, y_train)

# Faire des prédictions
y_pred_dt = decision_tree.predict(X_test)
y_pred_rf = random_forest.predict(X_test)

# Évaluer les modèles

# ... (Code pour l'instanciation, l'entraînement et la prédiction des modèles) ...

# Évaluer les modèles
for model_name, y_pred in [("Arbre de décision", y_pred_dt), ("Forêt aléatoire", y_pred_rf)]:
    print(f"\nÉvaluation de {model_name}:")

    # Matrice de confusion
    cm = confusion_matrix(y_test, y_pred)
    # Affichage sous forme de heatmap
    plt.figure(figsize=(6, 4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', linewidths=1, linecolor='black')
    plt.xlabel('Prédictions')
    plt.ylabel('Réel')
    plt.title(f'Matrice de Confusion de {model_name} ')
    plt.show()


    # Classification Report
    print("Classification Report:\n", classification_report(y_test, y_pred))

 # ... (Code pour afficher la courbe ROC) ...

    # Courbe ROC et AUC
    fpr, tpr, thresholds = roc_curve(y_test, y_pred)
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'ROC curve (area = {roc_auc:.2f}) - {model_name}')

"""**6.Validation simple et croisée**"""

#Validation simple
from sklearn.metrics import accuracy_score

# Evaluate with Accuracy
accuracy = accuracy_score(y_test, y_pred_rf)
print(f"Simple Validation Accuracy: {accuracy}")

#Validation et croisée

from sklearn.model_selection import cross_validate
score = cross_validate(random_forest, X, y, cv=5, scoring=['accuracy'])

print(f"Cross-Validation Scores: {score}")
print(f"Average Cross-Validation Accuracy: {score['test_accuracy'].mean()}") # Access the 'test_accuracy' key to get the accuracy scores and then calculate the mean

"""**7.Optimisation des hyperparamètres**"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, ShuffleSplit

# Définir la validation croisée (6 splits, 30% des données en test)
cv = ShuffleSplit(n_splits=6, test_size=0.3, random_state=0)

# Définir la grille de recherche des hyperparamètres
param_grid = {
    "n_estimators": [50, 100, 200],  # Nombre d'arbres dans la forêt
    "max_depth": np.arange(1, 20),   # Profondeur maximale de l’arbre
}

# Initialiser le modèle de Random Forest
rf_model = RandomForestClassifier(random_state=0)

# Lancer la recherche d'hyperparamètres avec validation croisée
grid_search = GridSearchCV(rf_model, param_grid, cv=cv, scoring="accuracy", n_jobs=-1)
grid_search.fit(X, y)

# Accéder aux meilleurs hyperparamètres
best_params = grid_search.best_params_
best_params

# Accéder au meilleur score
best_score = grid_search.best_score_
best_score

"""**5.Sauvegarde du modèle le plus performant**"""

# Instancier le modèle avec les meilleurs hyperparamètres
random_forest = RandomForestClassifier(n_estimators=200, max_depth=19)
# Entraîner les modèles
random_forest.fit(X_train, y_train)

#Sauvegarde du modèle
import joblib

# ... (Code pour l'entraînement du modèle de forêt aléatoire) ...

# Sauvegarder le modèle
joblib.dump(random_forest, 'random_forest_model.pkl')

# tester la prédiction d'un jeu de données

import pandas as pd
from joblib import load

loaded_model = load('random_forest_model.pkl')

# Use .iloc to select the first row as a DataFrame, then access its values and reshape
prediction = loaded_model.predict(X_test.iloc[[1]].values.reshape(1, -1))
print("Prediction:", prediction)

"""** 8.Archivage avec WandB**"""

!pip install wandb

import wandb
from wandb.integration.keras import WandbMetricsLogger
import joblib

wandb.login()

# création du projet, avec un nom de run
wandb.init(project="ECC-pre", name="arbre de décision - jeu 2", reinit=True)

# résultat à archiver
report = classification_report(y_test, y_pred_rf,  output_dict=True)

#config à archiver
config = {
    "max_depth": 10,
}

wandb.config.update(config)

# log des résultats
# log des résultats
# Accessing the report with the correct key '-1.0' instead of '-1'
wandb.log({"precision_class_0": report["-1.0"]["precision"],
           "recall_class_0": report["-1.0"]["recall"],
           "f1_class_0": report["-1.0"]["f1-score"]})
wandb.log({"precision_class_1": report["1.0"]["precision"],
           "recall_class_1": report["1.0"]["recall"],
           "f1_class_1": report["1.0"]["f1-score"]})

#archiver le modèle dans le run
loaded_model = 'random_forest_model.pkl'
joblib.dump(random_forest, loaded_model)
wandb.save(loaded_model)
# archiver le modèle dans le model registry de wandb
artifact = wandb.Artifact("arbrededecision", type="model")
artifact.add_file(loaded_model)
wandb.log_artifact(artifact)

wandb.finish()